version: '3.8'

services:
  app:
    build: .
    ports:
      - "8021:8021"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://test:test@mongodb:27017/board?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: board
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
