services:
  choi7907-springboot:
    container_name: choi7907-springboot
    build: .
    ports:
      - "21090:8021"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:rootpassword@choi7907-mongodb:27017/board?authSource=admin&authMechanism=SCRAM-SHA-256
    depends_on:
      - choi7907-mongodb
    networks:
      - npm-network

  choi7907-mongodb:
    container_name: choi7907-mongodb
    image: mongo:latest
    ports:
      - "21200:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: board
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - npm-network

volumes:
  mongodb_data:

networks:
  npm-network:
    external: true
