spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  application:
    name: board
  data:
    mongodb:
      database: board
      uri: mongodb://test:test@localhost:27017/board?authSource=admin
server:
  port: 8021
