spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  application:
    name: board
  data:
    mongodb:
      database: board
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpassword@localhost:21200/board?authSource=admin&authMechanism=SCRAM-SHA-256}
server:
  port: 8021
